name = (input('Enter your name '))
school = (input('Enter your schools name '))
Class = (input('Enter your class '))
address1 = (input('Enter your first address line '))
address2 = (input('Enter your second address line '))
roll = int(input('Enter your roll number '))
sect = (input('Enter your section '))
city = (input('Enter your city '))
pin = int(input('Enter your pin code  '))
parents = int(input('Enter your parents contact number '))
print('                    ',school)
print('')
print('Student name:',name,'           Roll No:',roll)
print('Class:',Class,'                 Section:',sect)
print('Address:',address1)
print('        ',address2)
print('')
print('City:  ',city,'        Pin code:',pin)
print('Parents/Guardians Contact No:',parents)